Enrollment No.: 240840116064

Practical 1

AIM: Study the Data Analytics lifecycle and perform data acquisition from CSV, Excel, and JSON files using Pandas.

Step 1: Import Pandas Library

In [1]:
#import pandas library
import pandas as pd

Step 2: Create dataFram

In [2]:
#create Dataset.
data = {
    "ID": [101, 102, 103, 104, 105, 106, 107],
    "Name": ["Rahul", "Priya", "Amit", "Riya", "Karan", "Krisha", "Harry"],
    "Age": [20, 21, 19, 20, 22, 24, 28 ],
    "City": ["Surat", "Navsari", "Valsad", "Bharuch", "Surat", "Gandhinagar", "Ahemdabad"],
    "Marks": [85, 92, 78, 88, 81, 84, 90]
}

Step 3: Create and Display Dataset

In [3]:
#create Dataset.
df = pd.DataFrame(data)
#Display Dataset.
df

    ID    Name  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21      Navsari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahemdabad     90

Step 4: Save DataFrame as CSV File

In [4]:
#Convert Dataframe to CSV File.
df.to_csv("students.csv", index=False)
#Display Dataset.
print("CSV file created successfully.")

CSV file created successfully.

Step 5: Save DataFrame as Excel File

In [5]:
#Convert Dataframe to Excel File.
df.to_excel("students.xlsx", index=False)

#Display Dataset.
print("Excel file created successfully.")

Excel file created successfully.

Step 6: Save DataFrame as JSON File

In [6]:
#Convert Dataframe to JSON File.
df.to_json("students.json",orient="records", index=4)

#Display Dataset.
print("JSON file created successfully.")

JSON file created successfully.

Step 7: Read CSV File

In [7]:
#Read csv File in a new DataFram.
df_csv = pd.read_csv("students.csv")
#display
df_csv

    ID    Name  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21      Navsari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahemdabad     90

Step 8: Read Excel File

In [8]:
#Read Exel File in a new DataFram.
df_excel = pd.read_excel("students.xlsx")
#display
df_excel

    ID    Name  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21      Navsari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahemdabad     90

Step 9: Read JSON File

In [9]:
#Read json File in a new DataFram.
df_json = pd.read_json("students.json")
#display
df_json

    ID    Name  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21      Navsari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahemdabad     90

Step 10: Inspect the Dataset

In [10]:
#Disply first five records.
df_csv.head()

    ID   Name  Age     City  Marks
0  101  Rahul   20    Surat     85
1  102  Priya   21  Navsari     92
2  103   Amit   19   Valsad     78
3  104   Riya   20  Bharuch     88
4  105  Karan   22    Surat     81

In [11]:
#disply last five records.
df_csv.tail()

    ID    Name  Age         City  Marks
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahemdabad     90

In [12]:
# Display information about the DataFram.

df_csv.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      7 non-null      int64
 1   Name    7 non-null      object
 2   Age     7 non-null      int64
 3   City    7 non-null      object
 4   Marks   7 non-null      int64
dtypes: int64(3), object(2)
memory usage: 412.0+ bytes

In [13]:
#Display descriptive statistical for numerical colomn

df_csv.describe()

               ID        Age      Marks
count    7.000000   7.000000   7.000000
mean   104.000000  22.000000  85.428571
std      2.160247   3.109126   4.961759
min    101.000000  19.000000  78.000000
25%    102.500000  20.000000  82.500000
50%    104.000000  21.000000  85.000000
75%    105.500000  23.000000  89.000000
max    107.000000  28.000000  92.000000

In [14]:
#diaplay the shape of Dataset. (No. of rows and No. of columns)

df_csv.shape

(7, 5)

In [15]:
#Display all column names.

df_csv.columns

Index(['ID', 'Name', 'Age', 'City', 'Marks'], dtype='object')

In [16]:
#Display the data type of each coloumn.

df_csv.dtypes

ID        int64
Name     object
Age       int64
City     object
Marks     int64
dtype: object

Step 11: Check For Missing Value

In [17]:
#Count the missing values in each column.

df_csv.isnull().sum()

ID       0
Name     0
Age      0
City     0
Marks    0
dtype: int64

Step 12: Display single column

In [18]:
#Display only the 'Marks' column.

df_csv["Marks"]

0    85
1    92
2    78
3    88
4    81
5    84
6    90
Name: Marks, dtype: int64

Step 13: Display Multiple Columns

In [19]:
#Display only the 'Name' and 'Marks' column.

df_csv[["Name","Marks"]]

     Name  Marks
0   Rahul     85
1   Priya     92
2    Amit     78
3    Riya     88
4   Karan     81
5  Krisha     84
6   Harry     90

Step 14: Filter Records

In [20]:
#DIsplay students whose marks are grater than 80.

df_csv[df_csv["Marks"]>80]

    ID    Name  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21      Navsari     92
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahemdabad     90

Step 15: Average Data

In [21]:
#Calculate the AVERAGE marks of the 'Marks' column.

df_csv["Marks"].mean()

np.float64(85.42857142857143)

Step 16: Sort Data

In [22]:
#Sort the dataset in decending order of marks.

df_csv.sort_values(by="Marks", ascending=False)

    ID    Name  Age         City  Marks
1  102   Priya   21      Navsari     92
6  107   Harry   28    Ahemdabad     90
3  104    Riya   20      Bharuch     88
0  101   Rahul   20        Surat     85
5  106  Krisha   24  Gandhinagar     84
4  105   Karan   22        Surat     81
2  103    Amit   19       Valsad     78

Step 17:Show All Data

In [23]:
# Display all dataset.

print(df_csv)

    ID    Name  Age         City  Marks
0  101   Rahul   20        Surat     85
1  102   Priya   21      Navsari     92
2  103    Amit   19       Valsad     78
3  104    Riya   20      Bharuch     88
4  105   Karan   22        Surat     81
5  106  Krisha   24  Gandhinagar     84
6  107   Harry   28    Ahemdabad     90