**Enrollment No.: 240840116064**

**Practical 8**

**Create interactive visualizations using Plotly Express and Plotly Graph
Objects.**

**Step 1: Import Required Libraries**

In [18]:
# Import Pandas.
import pandas as pd

# Import Plotly Express.
import plotly.express as px

# Import Ploty Graph Objects.
import plotly.graph_objects as go

**Step 2: Create Dataset**

In [19]:
data = {
    "Month": ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" ],
    "Product": ["Laptop", "Mobile", "Tablet", "Laptop", "Mobile", "Tablet", "Laptop", "Mobile", "Tablet", "Laptop", "Mobile", "Tablet"],
    "Region": ["North", "South", "East", "West", "North", "South", "East", "West", "North", "South", "East", "West"],
    "Sales": [120000, 135000, 150000, 145000, 160000, 175000, 180000, 170000, 190000, 210000, 2300010, 250000],
    "Units_Sold": [12, 30, 25, 14, 35, 30, 18, 38, 32, 21, 45, 40],
    "Profit": [18000, 27000, 30000, 22000, 32000, 35000, 28000, 34000, 38000, 33000, 46000, 50000]
}
df = pd.DataFrame(data)
df

        Month Product Region    Sales  Units_Sold  Profit
0     January  Laptop  North   120000          12   18000
1    February  Mobile  South   135000          30   27000
2       March  Tablet   East   150000          25   30000
3       April  Laptop   West   145000          14   22000
4         May  Mobile  North   160000          35   32000
5        June  Tablet  South   175000          30   35000
6        July  Laptop   East   180000          18   28000
7      August  Mobile   West   170000          38   34000
8   September  Tablet  North   190000          32   38000
9     October  Laptop  South   210000          21   33000
10   November  Mobile   East  2300010          45   46000
11   December  Tablet   West   250000          40   50000

**Step 3: Inspect the Dataset**

In [20]:
# Display First Five Columns.
df.head()

      Month Product Region   Sales  Units_Sold  Profit
0   January  Laptop  North  120000          12   18000
1  February  Mobile  South  135000          30   27000
2     March  Tablet   East  150000          25   30000
3     April  Laptop   West  145000          14   22000
4       May  Mobile  North  160000          35   32000

In [21]:
# Display No. of Rows and Columns.
df.shape

(12, 6)

In [22]:
# Display Information od dataset.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Month       12 non-null     object
 1   Product     12 non-null     object
 2   Region      12 non-null     object
 3   Sales       12 non-null     int64
 4   Units_Sold  12 non-null     int64
 5   Profit      12 non-null     int64
dtypes: int64(3), object(3)
memory usage: 708.0+ bytes

**Step 4: Create an Interactive Line chart using Plotly Explore**

In [23]:
# How does the sales revenue change throughout the year?
fig = px.line(df, x="Month", y="Sales", title="Sales Revenue Over Time")
fig.show()

**Step 5: Improve the Hover Information**

In [24]:
# Create a Line Chart using a Sales over Month.
fig = px.line(df, x='Month', y='Sales', title='Sales Over Month', markers=True)
fig.show()

In [25]:
# Add additional columns to the hover information. Student can see Product, Region, Units Sold and Profit when they move the mouse over a data point.
import plotly.express as px
fig = px.line(df,x="Month",y="Sales",markers=True,title="Monthly Sales Trend with Extra Hover Details",hover_data=["Profit", "Units_Sold", "Region"])
fig.show()

**Step 6: Create an Interective Bar Chart**

In [26]:
# Group the datset accordimg to Product.
product_sales = df.groupby('Product')['Sales'].sum().reset_index()

In [27]:
# Calculate the total Sales generated by each product.
df.groupby('Product')['Sales'].sum().reset_index()

  Product    Sales
0  Laptop   655000
1  Mobile  2765010
2  Tablet   765000

In [28]:
# Create an interective bar chart.
fig = px.bar(
    product_sales,
    x='Product',
    y='Sales',
    title='Total Sales by Product',
    labels={'Sales': 'Total Sales ($)', 'Product': 'Product Name'},
    text_auto='.2s'
)
fig.show()

**Step 7: Interective Scatter Plot**

In [29]:
# TO analyze the relationship between Units Sold and Sales Using an Interective Scatter Plot.
fig = px.scatter(
    df,
    x="Units_Sold",
    y="Sales",
    title="Units Sold vs Sales",
    labels={"Units_Sold": "Units Sold", "Sales": "Sales ($)"}
)
fig.show()

**Step 8: Interective Scatter Plot with Color**

In [30]:
# Create an interactive scatter plot with color
fig = px.scatter(
    df,
    x="Units_Sold",
    y="Sales",
    color="Product",
    title="Units Sold vs Sales by Product",
    labels={"Units_Sold": "Units Sold", "Sales": "Sales ($)"}
)
fig.show()

**Step 9: Save thye Dataset**

In [31]:
# Save dataset in CSV file
df.to_csv("DAta_Analysis.csv", index=False)

print("CSV file saved Successfully")
# Download CSV file.
from google.colab import files

files.download("DAta_Analysis.csv")

CSV file saved Successfully