Enrollment No.: 2401840116064

Practical 2

AIM: Perform data insoection, cleaning, handling missing values duplicate record removal and the data transformation using pandas.

Step 1: Import Pandas Library

In [1]:
#import Pandas

import pandas as pd

Step 2: Create dataFram

In [2]:
#create Dataset.
data = {
    "ID": [101, 102, 103, 104, 104, 105, 106, 107],
    "Name": ["Rahul", "Priya", "Amit", None, "Riya", "Ajay", "Naresh", "Jenil"],
    "Age": [20, 21, None, 20, 20, 22, 23, 28 ],
    "City": ["Surat", "Navsari", "Surat", "Bharuch","Bharuch", "Navsari", "Surat", "Ahemdabad"],
    "Marks": [85, None, 78, 88, 88, 81, 90, 93]
}

df = pd.DataFrame(data)
df

    ID    Name   Age       City  Marks
0  101   Rahul  20.0      Surat   85.0
1  102   Priya  21.0    Navsari    NaN
2  103    Amit   NaN      Surat   78.0
3  104    None  20.0    Bharuch   88.0
4  104    Riya  20.0    Bharuch   88.0
5  105    Ajay  22.0    Navsari   81.0
6  106  Naresh  23.0      Surat   90.0
7  107   Jenil  28.0  Ahemdabad   93.0

Step 3: Inspect the dataset

In [3]:
#Display first five rows of the dataset.

df.head()

    ID   Name   Age     City  Marks
0  101  Rahul  20.0    Surat   85.0
1  102  Priya  21.0  Navsari    NaN
2  103   Amit   NaN    Surat   78.0
3  104   None  20.0  Bharuch   88.0
4  104   Riya  20.0  Bharuch   88.0

In [4]:
#Display the last rows of the dataset.

df.tail()

    ID    Name   Age       City  Marks
3  104    None  20.0    Bharuch   88.0
4  104    Riya  20.0    Bharuch   88.0
5  105    Ajay  22.0    Navsari   81.0
6  106  Naresh  23.0      Surat   90.0
7  107   Jenil  28.0  Ahemdabad   93.0

In [5]:
#Display detailed information of dataset.

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ID      8 non-null      int64
 1   Name    7 non-null      object
 2   Age     7 non-null      float64
 3   City    8 non-null      object
 4   Marks   7 non-null      float64
dtypes: float64(2), int64(1), object(2)
memory usage: 452.0+ bytes

In [6]:
#Generate the Statistical information for the numerical columns.

df.describe()

           ID        Age      Marks
count    8.00   7.000000   7.000000
mean   104.00  22.000000  86.142857
std      2.00   2.886751   5.209881
min    101.00  20.000000  78.000000
25%    102.75  20.000000  83.000000
50%    104.00  21.000000  88.000000
75%    105.25  22.500000  89.000000
max    107.00  28.000000  93.000000

In [7]:
#Display yhe dimenstions of the dataset.

df.shape

(8, 5)

In [8]:
#DIsplay the datatype of each columns.

df.dtypes

ID         int64
Name      object
Age      float64
City      object
Marks    float64
dtype: object

In [9]:
#Display all the column of the dataFrame.

df.columns

Index(['ID', 'Name', 'Age', 'City', 'Marks'], dtype='object')

Step 4: Check Missing Values

In [10]:
#Check for the missing values in every columns.

df.isnull()

      ID   Name    Age   City  Marks
0  False  False  False  False  False
1  False  False  False  False   True
2  False  False   True  False  False
3  False   True  False  False  False
4  False  False  False  False  False
5  False  False  False  False  False
6  False  False  False  False  False
7  False  False  False  False  False

In [11]:
#Print null values for each columns.

df.isnull().sum()

ID       0
Name     1
Age      1
City     0
Marks    1
dtype: int64

In [12]:
#print total number of null values in dataset

df.isnull().sum().sum()

np.int64(3)

Step 5: Fill the missing values

In [13]:
# Replace the missing values in the Marks column.

df["Marks"] = df["Marks"].fillna(df["Marks"].mean())

#Display the updated DataFrame.
df

    ID    Name   Age       City      Marks
0  101   Rahul  20.0      Surat  85.000000
1  102   Priya  21.0    Navsari  86.142857
2  103    Amit   NaN      Surat  78.000000
3  104    None  20.0    Bharuch  88.000000
4  104    Riya  20.0    Bharuch  88.000000
5  105    Ajay  22.0    Navsari  81.000000
6  106  Naresh  23.0      Surat  90.000000
7  107   Jenil  28.0  Ahemdabad  93.000000

In [14]:
#Replace Missing value in the Age column.

df["Age"] = df["Age"].fillna(df["Age"].mean())
#Display the updated DataFrame.
df

    ID    Name   Age       City      Marks
0  101   Rahul  20.0      Surat  85.000000
1  102   Priya  21.0    Navsari  86.142857
2  103    Amit  22.0      Surat  78.000000
3  104    None  20.0    Bharuch  88.000000
4  104    Riya  20.0    Bharuch  88.000000
5  105    Ajay  22.0    Navsari  81.000000
6  106  Naresh  23.0      Surat  90.000000
7  107   Jenil  28.0  Ahemdabad  93.000000

In [15]:
#Replace the missing Names with the text "unknown".
df["Name"] = df["Name"].fillna("Unknown")
#Display the updated DataFrame.
df

    ID     Name   Age       City      Marks
0  101    Rahul  20.0      Surat  85.000000
1  102    Priya  21.0    Navsari  86.142857
2  103     Amit  22.0      Surat  78.000000
3  104  Unknown  20.0    Bharuch  88.000000
4  104     Riya  20.0    Bharuch  88.000000
5  105     Ajay  22.0    Navsari  81.000000
6  106   Naresh  23.0      Surat  90.000000
7  107    Jenil  28.0  Ahemdabad  93.000000

Step 6:Detect the duplicate value.

In [16]:
#Detect the duplicate value.
#Display the updated DataFrame.
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
dtype: bool

In [17]:
#Count the total number of duplicate rows.
df.duplicated().sum()
#Display the updated DataFrame.
df

    ID     Name   Age       City      Marks
0  101    Rahul  20.0      Surat  85.000000
1  102    Priya  21.0    Navsari  86.142857
2  103     Amit  22.0      Surat  78.000000
3  104  Unknown  20.0    Bharuch  88.000000
4  104     Riya  20.0    Bharuch  88.000000
5  105     Ajay  22.0    Navsari  81.000000
6  106   Naresh  23.0      Surat  90.000000
7  107    Jenil  28.0  Ahemdabad  93.000000

Step 7: Remove the duplicate records

In [18]:
# Delete duplicate data.
df.drop_duplicates(inplace=True)
#Display the updated DataFrame.
df

    ID     Name   Age       City      Marks
0  101    Rahul  20.0      Surat  85.000000
1  102    Priya  21.0    Navsari  86.142857
2  103     Amit  22.0      Surat  78.000000
3  104  Unknown  20.0    Bharuch  88.000000
4  104     Riya  20.0    Bharuch  88.000000
5  105     Ajay  22.0    Navsari  81.000000
6  106   Naresh  23.0      Surat  90.000000
7  107    Jenil  28.0  Ahemdabad  93.000000

Step 8: rename the column

In [19]:
#rename the column "Marks" to "Score"
df.rename(columns={"Marks": "Score"}, inplace=True)
#Display the updated DataFrame.
df

    ID     Name   Age       City      Score
0  101    Rahul  20.0      Surat  85.000000
1  102    Priya  21.0    Navsari  86.142857
2  103     Amit  22.0      Surat  78.000000
3  104  Unknown  20.0    Bharuch  88.000000
4  104     Riya  20.0    Bharuch  88.000000
5  105     Ajay  22.0    Navsari  81.000000
6  106   Naresh  23.0      Surat  90.000000
7  107    Jenil  28.0  Ahemdabad  93.000000

Step 9: Chnage Data Type

In [20]:
#Convert the age column from float to integer.
df["Age"] = df["Age"].astype(int)
#Display the updated DataFrame.
df.dtypes

ID         int64
Name      object
Age        int64
City      object
Score    float64
dtype: object

Step 10: Create a new column

In [21]:
#Create a new column names "Final Score".
df ["Final Score"] = df["Score"] + 5
#Display the updated DataFrame.
df

    ID     Name  Age       City      Score  Final Score
0  101    Rahul   20      Surat  85.000000    90.000000
1  102    Priya   21    Navsari  86.142857    91.142857
2  103     Amit   22      Surat  78.000000    83.000000
3  104  Unknown   20    Bharuch  88.000000    93.000000
4  104     Riya   20    Bharuch  88.000000    93.000000
5  105     Ajay   22    Navsari  81.000000    86.000000
6  106   Naresh   23      Surat  90.000000    95.000000
7  107    Jenil   28  Ahemdabad  93.000000    98.000000

Step 11: Convert text to upper case

In [22]:
#Student Name column to uppercase
df["Name"] = df["Name"].str.upper()
#Display the updated DataFrame.
df

    ID     Name  Age       City      Score  Final Score
0  101    RAHUL   20      Surat  85.000000    90.000000
1  102    PRIYA   21    Navsari  86.142857    91.142857
2  103     AMIT   22      Surat  78.000000    83.000000
3  104  UNKNOWN   20    Bharuch  88.000000    93.000000
4  104     RIYA   20    Bharuch  88.000000    93.000000
5  105     AJAY   22    Navsari  81.000000    86.000000
6  106   NARESH   23      Surat  90.000000    95.000000
7  107    JENIL   28  Ahemdabad  93.000000    98.000000

Step 12: Convert text into Lowercase

In [23]:
#Convert City into lowercase.
df["City"] = df["City"].str.lower()
#Display the updated DataFrame.
df

    ID     Name  Age       City      Score  Final Score
0  101    RAHUL   20      surat  85.000000    90.000000
1  102    PRIYA   21    navsari  86.142857    91.142857
2  103     AMIT   22      surat  78.000000    83.000000
3  104  UNKNOWN   20    bharuch  88.000000    93.000000
4  104     RIYA   20    bharuch  88.000000    93.000000
5  105     AJAY   22    navsari  81.000000    86.000000
6  106   NARESH   23      surat  90.000000    95.000000
7  107    JENIL   28  ahemdabad  93.000000    98.000000

Step 13: Remove Extra Space

In [24]:
#Remove Extra space form city column.
df["City"] = df["City"].str.strip()
#Display the updated DataFrame.
df

    ID     Name  Age       City      Score  Final Score
0  101    RAHUL   20      surat  85.000000    90.000000
1  102    PRIYA   21    navsari  86.142857    91.142857
2  103     AMIT   22      surat  78.000000    83.000000
3  104  UNKNOWN   20    bharuch  88.000000    93.000000
4  104     RIYA   20    bharuch  88.000000    93.000000
5  105     AJAY   22    navsari  81.000000    86.000000
6  106   NARESH   23      surat  90.000000    95.000000
7  107    JENIL   28  ahemdabad  93.000000    98.000000

Step 14: Sort the Dataset

In [25]:
#Sort the dataset based on final score.
df.sort_values(by=["Final Score"])
#Display the updated DataFrame.
df

    ID     Name  Age       City      Score  Final Score
0  101    RAHUL   20      surat  85.000000    90.000000
1  102    PRIYA   21    navsari  86.142857    91.142857
2  103     AMIT   22      surat  78.000000    83.000000
3  104  UNKNOWN   20    bharuch  88.000000    93.000000
4  104     RIYA   20    bharuch  88.000000    93.000000
5  105     AJAY   22    navsari  81.000000    86.000000
6  106   NARESH   23      surat  90.000000    95.000000
7  107    JENIL   28  ahemdabad  93.000000    98.000000

Step 15:Save the CleanData

In [26]:
# Save the cleaned DataFrame
df.to_csv('Cleaned_Students.csv', index=False)

# Display the updated DataFrame
df

    ID     Name  Age       City      Score  Final Score
0  101    RAHUL   20      surat  85.000000    90.000000
1  102    PRIYA   21    navsari  86.142857    91.142857
2  103     AMIT   22      surat  78.000000    83.000000
3  104  UNKNOWN   20    bharuch  88.000000    93.000000
4  104     RIYA   20    bharuch  88.000000    93.000000
5  105     AJAY   22    navsari  81.000000    86.000000
6  106   NARESH   23      surat  90.000000    95.000000
7  107    JENIL   28  ahemdabad  93.000000    98.000000