**Enrollmrnt No.: 240840116064**

**PRACTICAL 3**

**AIM: Apply ltering, sorting, aggregation, and GroupBy operations on real-world datasets.**

**Step 1: Display Dataset**

In [31]:
# Import Library.
import pandas as pd
# Create Dataset.
df = {
    "EMP_ID": [101, 102, 103, 104, 105, 106, 107, 108],
    "Name": ["Rahul", "Priya", "Amit", "Riya", "Karan", "Neha", "Vivek", "Pooja"],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "Finance", "IT", "HR"],
    "City": ["Surat", "Navasari", "Surat", "Valsad", "Surat", "Navasari", "Valsad", "Surat"],
    "Salary": [45000, 38000, 52000, 48000, 40000, 51000, 60000, 42000],
    "Experience": [2, 1, 5, 4, 2, 6, 8, 3]
}

df=pd.DataFrame(df)
df

   EMP_ID   Name Department      City  Salary  Experience
0     101  Rahul         IT     Surat   45000           2
1     102  Priya         HR  Navasari   38000           1
2     103   Amit         IT     Surat   52000           5
3     104   Riya    Finance    Valsad   48000           4
4     105  Karan         HR     Surat   40000           2
5     106   Neha    Finance  Navasari   51000           6
6     107  Vivek         IT    Valsad   60000           8
7     108  Pooja         HR     Surat   42000           3

**Step 2: Filter Data**

In [32]:
# 2.1: Display employees from IT department.
df[df['Department'] == 'IT']

#Display
df

   EMP_ID   Name Department      City  Salary  Experience
0     101  Rahul         IT     Surat   45000           2
1     102  Priya         HR  Navasari   38000           1
2     103   Amit         IT     Surat   52000           5
3     104   Riya    Finance    Valsad   48000           4
4     105  Karan         HR     Surat   40000           2
5     106   Neha    Finance  Navasari   51000           6
6     107  Vivek         IT    Valsad   60000           8
7     108  Pooja         HR     Surat   42000           3

In [33]:
# 2.2 Display employees with salary > 50000.
df[df['Salary'] > 50000]

#Display
df

   EMP_ID   Name Department      City  Salary  Experience
0     101  Rahul         IT     Surat   45000           2
1     102  Priya         HR  Navasari   38000           1
2     103   Amit         IT     Surat   52000           5
3     104   Riya    Finance    Valsad   48000           4
4     105  Karan         HR     Surat   40000           2
5     106   Neha    Finance  Navasari   51000           6
6     107  Vivek         IT    Valsad   60000           8
7     108  Pooja         HR     Surat   42000           3

In [34]:
# 2.3 Display employees from Surat.
df[df['City'] == 'Surat']

#Display
df

   EMP_ID   Name Department      City  Salary  Experience
0     101  Rahul         IT     Surat   45000           2
1     102  Priya         HR  Navasari   38000           1
2     103   Amit         IT     Surat   52000           5
3     104   Riya    Finance    Valsad   48000           4
4     105  Karan         HR     Surat   40000           2
5     106   Neha    Finance  Navasari   51000           6
6     107  Vivek         IT    Valsad   60000           8
7     108  Pooja         HR     Surat   42000           3

In [35]:
# 2.4 Display employees from IT department having salary > 5000
df[(df['Department'] == 'IT') & (df['Salary'] > 50000)]

#Display
df

   EMP_ID   Name Department      City  Salary  Experience
0     101  Rahul         IT     Surat   45000           2
1     102  Priya         HR  Navasari   38000           1
2     103   Amit         IT     Surat   52000           5
3     104   Riya    Finance    Valsad   48000           4
4     105  Karan         HR     Surat   40000           2
5     106   Neha    Finance  Navasari   51000           6
6     107  Vivek         IT    Valsad   60000           8
7     108  Pooja         HR     Surat   42000           3

**Step 3: Sort Data**

In [36]:
# 3.1: Salary ascending
#sort employees by salary from lowest to highest
df_ascending = df.sort_values('Salary', ascending=True)

#Display
df_ascending

   EMP_ID   Name Department      City  Salary  Experience
1     102  Priya         HR  Navasari   38000           1
4     105  Karan         HR     Surat   40000           2
7     108  Pooja         HR     Surat   42000           3
0     101  Rahul         IT     Surat   45000           2
3     104   Riya    Finance    Valsad   48000           4
5     106   Neha    Finance  Navasari   51000           6
2     103   Amit         IT     Surat   52000           5
6     107  Vivek         IT    Valsad   60000           8

In [37]:
# 3.2: Salary descending
#sort employees by salary from highest to lowest
df_descending = df.sort_values('Salary', ascending=False)

#Display
df_descending

   EMP_ID   Name Department      City  Salary  Experience
6     107  Vivek         IT    Valsad   60000           8
2     103   Amit         IT     Surat   52000           5
5     106   Neha    Finance  Navasari   51000           6
3     104   Riya    Finance    Valsad   48000           4
0     101  Rahul         IT     Surat   45000           2
7     108  Pooja         HR     Surat   42000           3
4     105  Karan         HR     Surat   40000           2
1     102  Priya         HR  Navasari   38000           1

In [38]:
# 3.3: Department-wise and salary descending
#sort employee department wise and within each department sort salary in decending order
df_department_sort = df.sort_values(
    ['Department', 'Salary'],
    ascending=[True, False]
)

#Display
df_department_sort

   EMP_ID   Name Department      City  Salary  Experience
5     106   Neha    Finance  Navasari   51000           6
3     104   Riya    Finance    Valsad   48000           4
7     108  Pooja         HR     Surat   42000           3
4     105  Karan         HR     Surat   40000           2
1     102  Priya         HR  Navasari   38000           1
6     107  Vivek         IT    Valsad   60000           8
2     103   Amit         IT     Surat   52000           5
0     101  Rahul         IT     Surat   45000           2

**Step 4: Perform Aggrigation**

In [39]:
# 4.1 Calculate the total salary of all employees.
df_total_salary = df['Salary'].sum()

#Display
df_total_salary

np.int64(376000)

In [40]:
#4.2 Calculate thye avg salary of all employees.
df_avg_salary = df['Salary'].mean()

#Display
df_avg_salary

np.float64(47000.0)

In [41]:
# 4.3 Display max salary.
df_max_salary = df['Salary'].max()

#Display
df_max_salary

60000

In [42]:
# 4.4 Display lowest salary.
df_min_salary = df['Salary'].min()

#Display
df_min_salary

38000

In [43]:
# 4.5 Count the total no of employees.
df_employee_count = df['EMP_ID'].count()

#Display
df_employee_count

np.int64(8)

**Step 5: Perform GroupBy Operation**

In [44]:
# 5.1: Average salary of each department
# grp employees based on department and calculate the avg salary of each department.
df_avg_department = df.groupby('Department')['Salary'].mean().reset_index()

#Display
df_avg_department

  Department        Salary
0    Finance  49500.000000
1         HR  40000.000000
2         IT  52333.333333

In [45]:
# 5.2: Total salary of each department.
# Calculate the total salary paid by each dept.
df_total_department = df.groupby('Department')['Salary'].sum().reset_index()

#Display
df_total_department

  Department  Salary
0    Finance   99000
1         HR  120000
2         IT  157000

In [46]:
# 5.3: Highest salary in each department.
# Display the higest salary in each department.
df_max_department = df.groupby('Department')['Salary'].max().reset_index()

#Display
df_max_department

  Department  Salary
0    Finance   51000
1         HR   42000
2         IT   60000

In [47]:
# 5.4: Number of employees in each department.
# Count the no of employees in each dept.
df_count_department = df.groupby('Department')['EMP_ID'].count().reset_index()

#Display
df_count_department

  Department  EMP_ID
0    Finance       2
1         HR       3
2         IT       3

In [48]:
# 5.5: Average salary in each city.
# Calculate the avg salary of employee in each city.
df_avg_city = df.groupby('City')['Salary'].mean().reset_index()

#Display
df_avg_city

       City   Salary
0  Navasari  44500.0
1     Surat  44750.0
2    Valsad  54000.0

**Step 6: Multiple Aggrigation Function**

In [49]:
# 6.1 Apply multiple statistical function to the salary column each dept.
df_multiple = df.groupby('Department')['Salary'].agg(
    ['sum', 'mean', 'max', 'min', 'count']
).reset_index()

#Display
df_multiple

  Department     sum          mean    max    min  count
0    Finance   99000  49500.000000  51000  48000      2
1         HR  120000  40000.000000  42000  38000      3
2         IT  157000  52333.333333  60000  45000      3

**Step 7: Save the result and Download CSV file**

In [50]:
# Step 7: Save CSV
from google.colab import files

files.download("employee_salary_analysis.csv")